name: Build and populate cache

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *"
  push:
    paths:
      - "pkgs"
      - "**.lock"
      - ".github/workflows/build.yml"

jobs:
  build:
    name: Build (${{ matrix.system }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin
          - os: ubuntu-24.04-arm
            system: aarch64-linux

    permissions: {}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@7b7f14d320d6aacfb65bd1ef761566b3b69e474c # v2026-02-22

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: extersia
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build from the matrix
        run: |
          nix run nixpkgs#nix-fast-build -- \
            --no-nom \
            --skip-cached \
            --systems '${{ matrix.system }}' \
            --flake '.#hydraJobs.${{ matrix.system }}'
